FROM debian:10-slim
LABEL maintainer="Hadi Azami <iazami@outlook.com>"

RUN apt-get update && apt-get install -y tor obfs4proxy

USER debian-tor

EXPOSE 9061 9051

CMD ["tor", "-f", "/etc/tor/torrc"]
